services:
  db:
    image: postgres:16
    env_file: .env
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy

  web:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      # This value is baked into the JS the browser runs; use localhost so the BROWSER can reach your API.
      - VITE_API_BASE=http://localhost:8000
    command: sh -c "npm ci || npm i && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  pgdata: