# Development-specific overrides
services:
  nginx:
    volumes:
      # Mount the development nginx config
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
  
  seq:
    environment:
      # In development, use a simple password for admin account
      # Password: "admin123" (change in production)
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123