"""Initial CamelCase schema with TrainAsset and AssetLocationEvent tables

Revision ID: 001_initial_camelcase_schema
Revises: 
Create Date: 2025-01-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001_initial_camelcase_schema'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=False, server_default='0'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Categories_Id'), 'Categories', ['Id'], unique=False)
    op.create_index(op.f('ix_Categories_Name'), 'Categories', ['Name'], unique=True)
    
    op.create_table('TrackLines',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_TrackLines_Id'), 'TrackLines', ['Id'], unique=False)
    op.create_index(op.f('ix_TrackLines_Name'), 'TrackLines', ['Name'], unique=True)
    
    op.create_table('TrainAssets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AssetId', sa.String(length=100), nullable=True),
    sa.Column('RfidTagId', sa.String(length=100), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('RoadNumber', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('DateAdded', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_TrainAssets_Id'), 'TrainAssets', ['Id'], unique=False)
    op.create_index(op.f('ix_TrainAssets_AssetId'), 'TrainAssets', ['AssetId'], unique=False)
    op.create_index(op.f('ix_TrainAssets_RfidTagId'), 'TrainAssets', ['RfidTagId'], unique=True)
    op.create_index(op.f('ix_TrainAssets_RoadNumber'), 'TrainAssets', ['RoadNumber'], unique=False)
    
    op.create_table('Sections',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('TrackLineId', sa.Integer(), nullable=False),
    sa.Column('PositionX', sa.Float(), nullable=True),
    sa.Column('PositionY', sa.Float(), nullable=True),
    sa.Column('PositionZ', sa.Float(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['TrackLineId'], ['TrackLines.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Sections_Id'), 'Sections', ['Id'], unique=False)
    op.create_index(op.f('ix_Sections_TrackLineId'), 'Sections', ['TrackLineId'], unique=False)
    
    op.create_table('Accessories',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('CategoryId', sa.Integer(), nullable=False),
    sa.Column('ControlType', sa.String(length=20), nullable=False),
    sa.Column('Address', sa.String(length=50), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('TimedMs', sa.Integer(), nullable=True),
    sa.Column('SectionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryId'], ['Categories.Id'], ),
    sa.ForeignKeyConstraint(['SectionId'], ['Sections.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Accessories_Id'), 'Accessories', ['Id'], unique=False)
    op.create_index(op.f('ix_Accessories_Name'), 'Accessories', ['Name'], unique=False)
    op.create_index(op.f('ix_Accessories_SectionId'), 'Accessories', ['SectionId'], unique=False)
    
    op.create_table('AssetLocationEvents',
    sa.Column('EventId', sa.Integer(), nullable=False),
    sa.Column('AssetId', sa.Integer(), nullable=False),
    sa.Column('RfidTagId', sa.String(length=100), nullable=False),
    sa.Column('Location', sa.String(length=100), nullable=False),
    sa.Column('ReaderId', sa.String(length=100), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['AssetId'], ['TrainAssets.Id'], ),
    sa.PrimaryKeyConstraint('EventId')
    )
    op.create_index(op.f('ix_AssetLocationEvents_EventId'), 'AssetLocationEvents', ['EventId'], unique=False)
    op.create_index(op.f('ix_AssetLocationEvents_AssetId'), 'AssetLocationEvents', ['AssetId'], unique=False)
    op.create_index(op.f('ix_AssetLocationEvents_RfidTagId'), 'AssetLocationEvents', ['RfidTagId'], unique=False)
    op.create_index(op.f('ix_AssetLocationEvents_ReaderId'), 'AssetLocationEvents', ['ReaderId'], unique=False)
    op.create_index(op.f('ix_AssetLocationEvents_Timestamp'), 'AssetLocationEvents', ['Timestamp'], unique=False)
    
    op.create_table('Switches',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('AccessoryId', sa.Integer(), nullable=False),
    sa.Column('SectionId', sa.Integer(), nullable=False),
    sa.Column('Kind', sa.String(length=50), nullable=False),
    sa.Column('DefaultRoute', sa.String(length=50), nullable=True),
    sa.Column('Orientation', sa.Float(), nullable=True),
    sa.Column('PositionX', sa.Float(), nullable=True),
    sa.Column('PositionY', sa.Float(), nullable=True),
    sa.Column('PositionZ', sa.Float(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['AccessoryId'], ['Accessories.Id'], ),
    sa.ForeignKeyConstraint(['SectionId'], ['Sections.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Switches_Id'), 'Switches', ['Id'], unique=False)
    op.create_index(op.f('ix_Switches_Name'), 'Switches', ['Name'], unique=False)
    op.create_index(op.f('ix_Switches_AccessoryId'), 'Switches', ['AccessoryId'], unique=False)
    op.create_index(op.f('ix_Switches_SectionId'), 'Switches', ['SectionId'], unique=False)
    
    op.create_table('SectionConnections',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FromSectionId', sa.Integer(), nullable=False),
    sa.Column('ToSectionId', sa.Integer(), nullable=False),
    sa.Column('SwitchId', sa.Integer(), nullable=True),
    sa.Column('RouteInfo', sa.String(length=255), nullable=True),
    sa.Column('IsBidirectional', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['FromSectionId'], ['Sections.Id'], ),
    sa.ForeignKeyConstraint(['SwitchId'], ['Switches.Id'], ),
    sa.ForeignKeyConstraint(['ToSectionId'], ['Sections.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_SectionConnections_Id'), 'SectionConnections', ['Id'], unique=False)
    op.create_index(op.f('ix_SectionConnections_FromSectionId'), 'SectionConnections', ['FromSectionId'], unique=False)
    op.create_index(op.f('ix_SectionConnections_SwitchId'), 'SectionConnections', ['SwitchId'], unique=False)
    op.create_index(op.f('ix_SectionConnections_ToSectionId'), 'SectionConnections', ['ToSectionId'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SectionConnections_ToSectionId'), table_name='SectionConnections')
    op.drop_index(op.f('ix_SectionConnections_SwitchId'), table_name='SectionConnections')
    op.drop_index(op.f('ix_SectionConnections_FromSectionId'), table_name='SectionConnections')
    op.drop_index(op.f('ix_SectionConnections_Id'), table_name='SectionConnections')
    op.drop_table('SectionConnections')
    
    op.drop_index(op.f('ix_Switches_SectionId'), table_name='Switches')
    op.drop_index(op.f('ix_Switches_AccessoryId'), table_name='Switches')
    op.drop_index(op.f('ix_Switches_Name'), table_name='Switches')
    op.drop_index(op.f('ix_Switches_Id'), table_name='Switches')
    op.drop_table('Switches')
    
    op.drop_index(op.f('ix_AssetLocationEvents_Timestamp'), table_name='AssetLocationEvents')
    op.drop_index(op.f('ix_AssetLocationEvents_ReaderId'), table_name='AssetLocationEvents')
    op.drop_index(op.f('ix_AssetLocationEvents_RfidTagId'), table_name='AssetLocationEvents')
    op.drop_index(op.f('ix_AssetLocationEvents_AssetId'), table_name='AssetLocationEvents')
    op.drop_index(op.f('ix_AssetLocationEvents_EventId'), table_name='AssetLocationEvents')
    op.drop_table('AssetLocationEvents')
    
    op.drop_index(op.f('ix_Accessories_SectionId'), table_name='Accessories')
    op.drop_index(op.f('ix_Accessories_Name'), table_name='Accessories')
    op.drop_index(op.f('ix_Accessories_Id'), table_name='Accessories')
    op.drop_table('Accessories')
    
    op.drop_index(op.f('ix_Sections_TrackLineId'), table_name='Sections')
    op.drop_index(op.f('ix_Sections_Id'), table_name='Sections')
    op.drop_table('Sections')
    
    op.drop_index(op.f('ix_TrainAssets_RoadNumber'), table_name='TrainAssets')
    op.drop_index(op.f('ix_TrainAssets_RfidTagId'), table_name='TrainAssets')
    op.drop_index(op.f('ix_TrainAssets_AssetId'), table_name='TrainAssets')
    op.drop_index(op.f('ix_TrainAssets_Id'), table_name='TrainAssets')
    op.drop_table('TrainAssets')
    
    op.drop_index(op.f('ix_TrackLines_Name'), table_name='TrackLines')
    op.drop_index(op.f('ix_TrackLines_Id'), table_name='TrackLines')
    op.drop_table('TrackLines')
    
    op.drop_index(op.f('ix_Categories_Name'), table_name='Categories')
    op.drop_index(op.f('ix_Categories_Id'), table_name='Categories')
    op.drop_table('Categories')
    # ### end Alembic commands ###