"""Add maintenance fields to TrainAsset

Revision ID: 003_add_maintenance_fields
Revises: 002_add_connection_type_column
Create Date: 2024-09-15 00:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_add_maintenance_fields'
down_revision = '002_add_connection_type_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrainAssets', sa.Column('LastServicedDate', sa.DateTime(), nullable=True))
    op.add_column('TrainAssets', sa.Column('MaintenanceStatus', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrainAssets', 'MaintenanceStatus')
    op.drop_column('TrainAssets', 'LastServicedDate')
    # ### end Alembic commands ###