"""Initial schema with all tables

Revision ID: 66c926914d81
Revises: 
Create Date: 2025-09-10 03:55:55.943315

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '66c926914d81'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('trackLines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackLines_id'), 'trackLines', ['id'], unique=False)
    op.create_index(op.f('ix_trackLines_name'), 'trackLines', ['name'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trackLine_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['trackLine_id'], ['trackLines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_trackLine_id'), 'sections', ['trackLine_id'], unique=False)
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('control_type', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('timed_ms', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessories_id'), 'accessories', ['id'], unique=False)
    op.create_index(op.f('ix_accessories_name'), 'accessories', ['name'], unique=False)
    op.create_index(op.f('ix_accessories_section_id'), 'accessories', ['section_id'], unique=False)
    op.create_table('switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('default_route', sa.String(length=50), nullable=True),
    sa.Column('orientation', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_switches_accessory_id'), 'switches', ['accessory_id'], unique=False)
    op.create_index(op.f('ix_switches_id'), 'switches', ['id'], unique=False)
    op.create_index(op.f('ix_switches_section_id'), 'switches', ['section_id'], unique=False)
    op.create_table('sectionConnections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_section_id', sa.Integer(), nullable=False),
    sa.Column('to_section_id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('route_info', sa.String(length=255), nullable=True),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['from_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ),
    sa.ForeignKeyConstraint(['to_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectionConnections_from_section_id'), 'sectionConnections', ['from_section_id'], unique=False)
    op.create_index(op.f('ix_sectionConnections_id'), 'sectionConnections', ['id'], unique=False)
    op.create_index(op.f('ix_sectionConnections_switch_id'), 'sectionConnections', ['switch_id'], unique=False)
    op.create_index(op.f('ix_sectionConnections_to_section_id'), 'sectionConnections', ['to_section_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sectionConnections_to_section_id'), table_name='sectionConnections')
    op.drop_index(op.f('ix_sectionConnections_switch_id'), table_name='sectionConnections')
    op.drop_index(op.f('ix_sectionConnections_id'), table_name='sectionConnections')
    op.drop_index(op.f('ix_sectionConnections_from_section_id'), table_name='sectionConnections')
    op.drop_table('sectionConnections')
    op.drop_index(op.f('ix_switches_section_id'), table_name='switches')
    op.drop_index(op.f('ix_switches_id'), table_name='switches')
    op.drop_index(op.f('ix_switches_accessory_id'), table_name='switches')
    op.drop_table('switches')
    op.drop_index(op.f('ix_accessories_section_id'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_name'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_id'), table_name='accessories')
    op.drop_table('accessories')
    op.drop_index(op.f('ix_sections_trackLine_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_trackLines_name'), table_name='trackLines')
    op.drop_index(op.f('ix_trackLines_id'), table_name='trackLines')
    op.drop_table('trackLines')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
