#version: "3.8"
services:
  web:
    #image: ghcr.io/plausiblealibi/trainstation:latest
    build:
      context: ..
      dockerfile: docker/prod.Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - UVICORN_WORKERS=1
      - APP_MODULE=main:app      # <- your /app/main.py exposes `app`
      - UVICORN_RELOAD=          # empty disables dev reload in prod
    ports:
      - "8080:8000"              # host:container
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trains
      POSTGRES_USER: trainsAdmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-brokentrack}
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trainsAdmin -d trains || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  frontend:
      build:
        context: ../frontend   # path to your frontend project folder
        dockerfile: Dockerfile
      ports:
        - "3000:80"            # visit UI at http://localhost:3000
      depends_on:
        - web
      restart: unless-stopped
volumes:
  dbdata: