#version: "3.8"
services:
  web:
    image: ghcr.io/plausiblealibi/trainstation:latest   # <- set owner below
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trains
      POSTGRES_USER: trainsAdmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-brokentrack}
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dbdata: